import { image } from "framer-motion/client";

export const show = [
  {
    id: "1",
    name: "Nova Pro",
    edition: "Titanium Edition",
    image: "/phone.svg",
    discription: "Experience the world's most powerful camera system in a smartphone. Faster than ever.",
    price: 999.00,
  },
  {
    id: "2",
    name: "Nova Pro",
    edition: "Titanium Edition",
    image: "/laptop.svg",
    discription: "Experience the world's most powerful camera system in a smartphone. Faster than ever.",
    price: 1499.00,
  },
  {
    id: "3",
    name: "Nova Pro",
    edition: "Titanium Edition",
    image: "/headset.svg",
    discription: "Experience the world's most powerful camera system in a smartphone. Faster than ever.",
    price: 349.00,
  },
];

export const trending = [
  {
    id: "t1",
    name: "Acoustic Pro Gen 3",
    brand: "G-Tech",
    type: "AUDIO",
    category: "Headphones",
    image: "/Acoustic.svg",
    price: 299.00,
    rating: 5,
    reviews: 134,
  },
  {
    id: "t2",
    name: "Book Air 15",
    brand: "Apple",
    type: "LAPTOPS",
    category: "Laptop",
    image: "/Book.svg",
    price: 1299.00,
    rating: 5,
    reviews: 210,
  },
  {
    id: "t3",
    name: "Tab X Ultra",
    brand: "Samsung",
    type: "TABLETS",
    category: "Tablet",
    image: "/Tab.svg",
    price: 649.00,
    rating: 4,
    reviews: 89,
  },
  {
    id: "t4",
    name: "Pulse Watch 4",
    brand: "HealthTech",
    type: "WEARABLES",
    category: "Watch",
    image: "/Watch.svg",
    price: 199.00,
    rating: 4,
    reviews: 430,
  },
  {
    id: "t5",
    name: "Book Air 15",
    brand: "Apple",
    type: "LAPTOPS",
    category: "Laptop",
    image: "/Book.svg",
    price: 1299.00,
    rating: 5,
    reviews: 210,
  },
  {
    id: "t6",
    name: "Acoustic Pro Gen 3",
    brand: "G-Tech",
    type: "AUDIO",
    category: "Headphones",
    image: "/Acoustic.svg",
    price: 299.00,
    rating: 5,
    reviews: 134,
  },
];


export const AllProducts = [
  {
    id: 1,
    name: "MacBook Air M2",
    brand: "Apple",
    price: 1199.00,
    image: "/macbook.svg",
    rating: 5,
    reviews: 124,
    category: "Laptop",
    tag: "BEST SELLER",
  },
  {
    id: 2,
    name: "MacBook Air M2",
    brand: "Apple",
    price: 1199.00,
    image: "/macbook.svg",
    rating: 5,
    reviews: 124,
    category: "Watch",
    tag: "BEST SELLER",
  },
  {
    id: 3,
    name: "MacBook Air M2",
    brand: "Apple",
    price: 1199.00,
    image: "/macbook.svg",
    rating: 5,
    reviews: 124,
    category: "Laptop",
    tag: "BEST SELLER",
  },
  {
    id: 4,
    name: "WH-1000XM5",
    brand: "Sony",
    price: 348.00,
    image: "/wh.svg",
    rating: 5,
    reviews: 850,
    category: "Headphones",
    tag: null,
  },
  {
    id: 5,
    name: "WH-1000XM5",
    brand: "Sony",
    price: 348.00,
    image: "/wh.svg",
    rating: 5,
    reviews: 850,
    category: "Watch",
    tag: null,
  },
  {
    id: 6,
    name: "WH-1000XM5",
    brand: "Sony",
    price: 348.00,
    image: "/wh.svg",
    rating: 5,
    reviews: 850,
    category: "Smartphone",
    tag: null,
  },
  {
    id: 7,
    name: "XPS 15 Laptop",
    brand: "Dell",
    price: 1899.00,
    oldPrice: 2199.00,
    image: "/xps.svg",
    rating: 4,
    reviews: 56,
    category: "Laptop",
    tag: "15% OFF",
  },
  {
    id: 8,
    name: "XPS 15 Laptop",
    brand: "Dell",
    price: 1899.00,
    oldPrice: 2199.00,
    image: "/xps.svg",
    rating: 4,
    reviews: 56,
    category: "Smartphone",
    tag: "15% OFF",
  },
  {
    id: 9,
    name: "XPS 15 Laptop",
    brand: "Dell",
    price: 1899.00,
    oldPrice: 2199.00,
    image: "/xps.svg",
    rating: 4,
    reviews: 56,
    category: "Watch",
    tag: "15% OFF",
  },
  {
    id: 10,
    name: "XPS 15 Laptop",
    brand: "Dell",
    price: 1899.00,
    oldPrice: 2199.00,
    image: "/xps.svg",
    rating: 4,
    reviews: 56,
    category: "Laptop",
    tag: "15% OFF",
  },
  {
    id: 11,
    name: "Momentum 4",
    brand: "Sennheiser",
    price: 299.00,
    image: "/momentum.svg",
    rating: 5,
    reviews: 312,
    category: "Headphones",
    tag: null,
  },
  {
    id: 12,
    name: "Momentum 4",
    brand: "Sennheiser",
    price: 299.00,
    image: "/momentum.svg",
    rating: 5,
    reviews: 312,
    category: "Smartphone",
    tag: null,
  },
  {
    id: 13,
    name: "Momentum 4",
    brand: "Sennheiser",
    price: 299.00,
    image: "/momentum.svg",
    rating: 5,
    reviews: 312,
    category: "Watch",
    tag: null,
  },
  {
    id: 14,
    name: "Momentum 4",
    brand: "Sennheiser",
    price: 299.00,
    image: "/momentum.svg",
    rating: 5,
    reviews: 312,
    category: "Headphones",
    tag: null,
  },
  {
    id: 15,
    name: "Zenbook S 13",
    brand: "ASUS",
    price: 1399.00,
    image: "/zenbook.svg",
    rating: 4,
    reviews: 42,
    category: "Laptop",
    tag: null,
  },
  {
    id: 16,
    name: "Zenbook S 13",
    brand: "ASUS",
    price: 1399.00,
    image: "/zenbook.svg",
    rating: 4,
    reviews: 42,
    category: "Smartphone",
    tag: null,
  },
  {
    id: 17,
    name: "Zenbook S 13",
    brand: "ASUS",
    price: 1399.00,
    image: "/zenbook.svg",
    rating: 4,
    reviews: 42,
    category: "Watch",
    tag: null,
  },
  {
    id: 18,
    name: "QuietComfort Ultra",
    brand: "Bose",
    price: 429.00,
    image: "/quiet.svg",
    rating: 5,
    reviews: 208,
    category: "Headphones",
    tag: "LIMITED",
  },
  {
    id: 19,
    name: "QuietComfort Ultra",
    brand: "Bose",
    price: 429.00,
    image: "/quiet.svg",
    rating: 5,
    reviews: 208,
    category: "Smartphone",
    tag: "LIMITED",
  },
  {
    id: 20,
    name: "QuietComfort Ultra",
    brand: "Bose",
    price: 429.00,
    image: "/quiet.svg",
    rating: 5,
    reviews: 208,
    category: "Headphones",
    tag: "LIMITED",
  },
];


export const SideImg = [
  {
    id: 1,
    image: '/flat.svg',
  },
  {
    id: 2,
    image: '/control.svg',
  },
  {
    id: 3,
    image: '/usb.svg',
  },
  {
    id: 4,
    image: '/box.svg',
  },
]
export const related = [
  {
    id: "r1",
    name: 'G-Tech Wireless Controller',
    brand: 'G-Tech',
    category: 'Accessories',
    image: '/pad.svg',
    price: 1250.00,
    rating: 4,
    reviews: 65,
  },
  {
    id: "r2",
    name: 'Sonic Pro Audio Headset',
    brand: 'Sonic',
    category: 'Headphones',
    image: '/white.svg',
    price: 2250.00,
    rating: 5,
    reviews: 142,
  },
  {
    id: "r3",
    name: 'G-Tech Vertical Stand',
    brand: 'G-Tech',
    category: 'Accessories',
    image: '/wood.svg',
    price: 4250.00,
    rating: 4,
    reviews: 28,
  },
  {
    id: "r4",
    name: 'Ambient Light Sync Kit',
    brand: 'G-Tech',
    category: 'Accessories',
    image: '/light.svg',
    price: 7250.00,
    rating: 5,
    reviews: 95,
  },
];