
export const show = [
  {
    id: "1",
    name: "Nova Pro",
    edition: "Titanium Edition",
    image: "/phone.svg",
    discription: "Experience the world's most powerful camera system in a smartphone. Faster than ever.",
  },
  {
    id: "2",
    name: "Nova Pro",
    edition: "Titanium Edition",
    image: "/laptop.svg",
    discription: "Experience the world's most powerful camera system in a smartphone. Faster than ever.",
  },
  {
    id: "3",
    name: "Nova Pro",
    edition: "Titanium Edition",
    image: "/headset.svg",
    discription: "Experience the world's most powerful camera system in a smartphone. Faster than ever.",
  },
];

export const trending = [
  {
    id: "1",
    name: "Acoustic Pro Gen 3",
    type: "AUDIO",
    image: "/Acoustic.svg",
    price: "$299.00",
  },
  {
    id: "2",
    name: "Book Air 15",
    type: "LAPTOPS",
    image: "/Book.svg",
    price: "$1,299.00",
  },
  {
    id: "3",
    name: "Tab X Ultra",
    type: "TABLETS",
    image: "/Tab.svg",
    price: "$649.00",
  },
  {
    id: "4",
    name: " Pulse Watch 4",
    type: "WEAREABLES",
    image: "/Watch.svg",
    price: "$199.00",
  },
  {
    id: "5",
    name: "Book Air 15",
    type: "LAPTOPS",
    image: "/Book.svg",
    price: "$1,299.00",
  },
  {
    id: "6",
    name: "Acoustic Pro Gen 3",
    type: "AUDIO",
    image: "/Acoustic.svg",
    price: "$299.00",
  },
];


export const AllProducts = [
  {
    id: 1,
    name: "MacBook Air M2",
    brand: "Apple",
    price: 1199.00,
    image: "/macbook.svg",
    rating: 5,
    reviews: 124,
    category: "laptop",
    tag: "BEST SELLER",
  },
  {
    id: 2,
    name: "WH-1000XM5",
    brand: "Sony",
    price: 348.00,
    image: "/wh.svg",
    rating: 5,
    reviews: 850,
    category: "audio",
    tag: null,
  },
  {
    id: 3,
    name: "XPS 15 Laptop",
    brand: "Dell",
    price: 1899.00,
    oldPrice: 2199.00,
    image: "/xps.svg",
    rating: 4,
    reviews: 56,
    category: "laptop",
    tag: "15% OFF",
  },
  {
    id: 4,
    name: "Momentum 4",
    brand: "Sennheiser",
    price: 299.00,
    image: "/momentum.svg",
    rating: 5,
    reviews: 312,
    category: "audio",
    tag: null,
  },
  {
    id: 5,
    name: "Zenbook S 13",
    brand: "ASUS",
    price: 1399.00,
    image: "/zenbook.svg",
    rating: 4,
    reviews: 42,
    category: "laptop",
    tag: null,
  },
  {
    id: 6,
    name: "QuietComfort Ultra",
    brand: "Bose",
    price: 429.00,
    image: "/quiet.svg",
    rating: 5,
    reviews: 208,
    category: "audio",
    tag: "LIMITED",
  }
];